databases:
  - name: psychiatric_website
    databaseName: banking
    user: banking

services:
  - type: web
    name: psychiatric_website
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn psychiatric_website.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mysite
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4